### ISSUE TITLE
Make a release, push to Zenodo, get a DOI 

### ISSUE THREAD

**Issue by cranmer** [cocoa-hep/cocoa-hep#30]
Would be nice to have a DOI so that we could cite this repo in a paper. 
https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

**Comment by sanmayphy** [comment]
done

**Comment by cranmer** [comment]
That's great. We should update the reference to the code in the paper to be a citation that uses the DOI instead of a footnote.
